"use strict";

module.exports = {
  walk: {
    invisibleElements: [
      "applet",
      "area",
      "audio",
      "base",
      "basefont",
      "bdi",
      "bdo",
      "big",
      "br",
      "center",
      "colgroup",
      "datalist",
      "form",
      "frameset",
      "head",
      "link",
      "map",
      "meta",
      "noframes",
      "noscript",
      "optgroup",
      "option",
      "param",
      "rp",
      "rt",
      "ruby",
      "script",
      "source",
      "style",
      "title",
      "track",
      "xmp",
    ],
    ignoreChildrenElements: [
      "img",
      "canvas",
      "input",
      "textarea",
      "audio",
      "video",
      "hr",
      "embed",
      "object",
      "progress",
      "select",
      "table",
    ],
    styleFilters: [
      "margin-left",
      "margin-top",
      "margin-right",
      "margin-bottom",
      "border-left-color",
      "border-left-style",
      "border-left-width",
      "border-top-color",
      "border-top-style",
      "border-top-width",
      "border-right-color",
      "border-right-style",
      "border-right-width",
      "border-bottom-color",
      "border-bottom-style",
      "border-bottom-width",
      "border-top-left-radius",
      "border-top-right-radius",
      "border-bottom-left-radius",
      "border-bottom-right-radius",
      "padding-left",
      "padding-top",
      "padding-right",
      "padding-bottom",
      "background-color",
      "background-image",
      "background-repeat",
      "background-size",
      "background-position",
      "list-style-image",
      "list-style-position",
      "list-style-type",
      "outline-color",
      "outline-style",
      "outline-width",
      "font-size",
      "font-family",
      "font-weight",
      "font-style",
      "line-height",
      "box-shadow",
      "clear",
      "color",
      "display",
      "float",
      "opacity",
      "text-align",
      "text-decoration",
      "text-indent",
      "text-shadow",
      "vertical-align",
      "visibility",
      "position",
    ],
    // attributes to mark an element
    attributeFilters: ["id", "class"],
    excludeSelectors: [],
    removeSelectors: [], // remove elements before walk
    ignoreTextSelectors: [], // ignore content change of text node or image change
    ignoreStyleSelectors: [], // ignore style change
    ignoreChildrenSelectors: [], //
    root: "body",
  },
};
